name: Deploy to Hosting
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: copy files to server     
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
            server: yurivanton.site
            username: anton.yurivanton.site
            password: AntonYuriv1!
